INSERT INTO backer_levels
(level_id,name,minimum_pledge,reward_details)
VALUES
(1,"Stargazer",1,"Backer Challenge Rewards"),
(2,"Colony Cadet",25,"Backer Challenge Rewards, Digital Copy, Exclusive Wallpapers"),
(3,"Space Farm Pioneer",45,"Backer Challenge Rewards, Digital Copy, Exclusive Wallpapers,
  Early Access, Name in Credits"),
(4,"Galactic Jammer",65,"Backer Challenge Rewards, Digital Copy, Exclusive Wallpapers,
  Early Access, Name in Credits, Digital OST"),
(5,"Forerunner",80,"Backer Challenge Rewards, Digital Copy, Exclusive Wallpapers,
  Early Access, Name in Credits, Digital OST, Monthly Alpha Builds"),
(6,"Space Farm Fanatic",120,"Backer Challenge Rewards, Digital Copy, Exclusive Wallpapers,
  Early Access, Name in Credits, Digital OST, Monthly Alpha Builds, VIP Discord, Signed Thank You Letter"),
(7,"Colony Builder",220,"Backer Challenge Rewards, Digital Copy, Exclusive Wallpapers,
  Early Access, Name in Credits, Digital OST, Monthly Alpha Builds, VIP Discord, Signed Thank You Letter,
  Design Committee Group Chat, Design a Furnishing"),
(8,"Future Fashion Designer - Hair Stylist",350,"Backer Challenge Rewards, Digital Copy, Exclusive Wallpapers,
  Early Access, Name in Credits, Digital OST, Monthly Alpha Builds, VIP Discord, Signed Thank You Letter,
  Design Committee Group Chat, Design a Furnishing, Design a Hairstyle"),
(9,"Future Fashion Designer - Tailor",500,"Backer Challenge Rewards, Digital Copy, Exclusive Wallpapers,
  Early Access, Name in Credits, Digital OST, Monthly Alpha Builds, VIP Discord, Signed Thank You Letter,
  Design Committee Group Chat, Design a Furnishing, Design a Hairstyle, Design an Outfit"),
(10,"Gene Splicer",600,"Backer Challenge Rewards, Digital Copy, Exclusive Wallpapers,
  Early Access, Name in Credits, Digital OST, Monthly Alpha Builds, VIP Discord, Signed Thank You Letter,
  Design Committee Group Chat, Design a Furnishing, Design a Hairstyle, Design an Outfit, Design a Crop"),
(11,"Cyber Rancher",750,"Backer Challenge Rewards, Digital Copy, Exclusive Wallpapers,
  Early Access, Name in Credits, Digital OST, Monthly Alpha Builds, VIP Discord, Signed Thank You Letter,
  Design Committee Group Chat, Design a Furnishing, Design a Hairstyle, Design an Outfit, Design a Crop,
  Design a Robo Farm Animal"),
(12,"Future Friends",1300,"Backer Challenge Rewards, Digital Copy, Exclusive Wallpapers,
  Early Access, Name in Credits, Digital OST, Monthly Alpha Builds, VIP Discord, Signed Thank You Letter,
  Design Committee Group Chat, Design a Furnishing, Design a Hairstyle, Design an Outfit, Design a Crop,
  Design a Robo Farm Animal, Design an NPC"),
(13,"Stellar Romantic",2000,"Backer Challenge Rewards, Digital Copy, Exclusive Wallpapers,
  Early Access, Name in Credits, Digital OST, Monthly Alpha Builds, VIP Discord, Signed Thank You Letter,
  Design Committee Group Chat, Design a Furnishing, Design a Hairstyle, Design an Outfit, Design a Crop,
  Design a Robo Farm Animal, Design an NPC, Design a Marriage Candidate"),
(14,"Melon Usk's Successor",5000,"Backer Challenge Rewards, Digital Copy, Exclusive Wallpapers,
  Early Access, Name in Credits, Digital OST, Monthly Alpha Builds, VIP Discord, Signed Thank You Letter,
  Design Committee Group Chat, Design a Furnishing, Design a Hairstyle, Design an Outfit, Design a Crop,
  Design a Robo Farm Animal, Design an NPC, Design a Marriage Candidate, Credited as Associate Producer,
  Exclusive Outfit for You");
